name: Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
      - uses: pre-commit/action@v3.0.1
